проходят тесты до 6-2 кроме 4-3(вроде делает что надо)
js-tasks-ru/jsbasic-20240919_leonid66 pull request #11
Opened 2024-10-19 17:41 UTC by leonidjscode4

2024-10-19 17:44 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-10-19 18:05 UTC, koalex requested changes
По **4-3** написал замечания в Telegram. И нужно решить **6-3**

2024-10-20 13:52 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-10-22 09:56 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-10-26 06:19 UTC, koalex requested changes
Опечатка в 6-3

2024-10-26 06:19 UTC, koalex commented on 6-module/3-task/index.js
> +            <div class="carousel__slide" data-id=${slide.id}">
Тут не хватает кавычки, сравните:
`<div class="carousel__slide" data-id=${slide.id}">` - ваша строка

`<div class="carousel__slide" data-id="${slide.id}">` - правильная строка

(перед ${slide.id} кавычка)

2024-10-26 08:05 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-10-26 08:07 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @koalex

2024-10-26 12:11 UTC, koalex approved these changes

2024-10-26 12:12 UTC, merged